name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build -- --configuration production

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TAIPAPA_WEBSITE }}
          channelId: live
          projectId: taipapa-website

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "✅ Firebase deploy succeeded!"
          to: lichungtsai611@gmail.com
          from: GitHub Deploy Bot <lichungtsai611@gmail.com>
          body: |
            🎉 Your Angular website has been successfully deployed!

            🔗 Visit it here: https://taipapa-website.web.app

            -- From your GitHub Actions bot 🤖
